### ISSUE TITLE
Invoice Overview Templates

### ISSUE THREAD

**Issue by datawiki** [oteloegen/SemanticOrganization#3]
The Invoice [Overview Template](https://semorg.kollabor.at/wiki/Invoices/en) example is missing something. Although there are four Invoices, the all, open, and due filters find "no entries so far". The template filter lists one in square brackets but does not pick up field values.

It did work before Invoice Templates (wonderful addition) were added.
![SOrg1](https://user-images.githubusercontent.com/19792343/128345340-dede3bf7-ab72-4dee-8aa0-b97ead89f56f.png)

**Comment by thaider** [comment]
There were some problems with the documentation that should be fixed now...
