### ISSUE TITLE
Page Edit Button does not work

### ISSUE THREAD

**Issue by datawiki** [oteloegen/SemanticOrganization#4]
Hi
**The Edit page button does not work.** 
Edit Section does work.
![SOrg2](https://user-images.githubusercontent.com/19792343/130755285-32d6f5b6-c152-4a28-9176-970458b48a93.png)
Fresh Mediawiki 1.35 master install. Also Semorg and Tweeki master install. Logged in as WikiSysop Administrators, Autoconfirmed users, Bureaucrats, Interface administrators, Users rights.
$wgGroupPermissions['sysop']['read'] = true;
$wgGroupPermissions['sysop']['edit'] = true;
$wgGroupPermissions['sysop']['delete'] = true;
$wgGroupPermissions['sysop']['createpage'] = true;

$wgTweekiSkinUseBootstrap4 = true;
$wgTweekiSkinHideable[] = 'sidebar-right'; 
$wgTweekiSkinHideAnon['EDIT-EXT'] = true;  
$wgTweekiSkinHideAnon['subnav'] = true;
$wgTweekiSkinHideAnon['subnav'] = true;
$wgTweekiSkinUseTooltips = true;
$wgTweekiSkinUseBtnParser = true;
$wgTweekiSkinUseAwesome = true;

**Comment by thaider** [comment]
Thanks for reporting. This was a problem with Tweeki skin that should be fixed now.
