### ISSUE TITLE
The templates can not be properly used

### ISSUE THREAD

**Issue by JayLiu7319** [oteloegen/SemanticOrganization#5]
Hi, I found this repo because of your Semanti Organization project. This work is excellent and impressive! But when I use the organization extension, some fatal error occured. 
I'm using tweeki skin and it works well in my website. I followed the installion guide and when I use the templates from the organization extension, I can't get the proper result as your site https://semorg.kollabor.at/wiki/Groups.
Maybe I missing some important components? Such as some custom file?

![image](https://user-images.githubusercontent.com/16852190/147328773-fd1a519c-8da9-4d22-b7e7-e1581c8fcb6f.png)

**Comment by thaider** [comment]
Please don't post your issues in several places. See my answer [here](https://github.com/thaider/SemanticOrganization-Docker/issues/2#issuecomment-1000822851).
