### ISSUE TITLE
Form and Templates gives error 

### ISSUE THREAD

**Issue by HQ1791** [oteloegen/SemanticOrganization#6]
I have MediaWiki 1.39, Semantic MediaWiki 1.40, Tweeki, Parser and I have installed Semantic-Organization so i can test forms.  For testing i used below form in a simple page:

`{{#semorg-forminput:group}}` 

looks like this:
![SO1](https://github.com/thaider/SemanticOrganization/assets/129038344/0de65759-8b7b-45d3-baac-ae1cda8b3e5c)

when i enter a group name it give me this error.
![SO2](https://github.com/thaider/SemanticOrganization/assets/129038344/f3a9ba15-9718-4613-858b-f10f296de25c)

I don't understand what exactly is the issue. Could you help me to solve this issue?

**Comment by thaider** [comment]
Please note that SemanticOrganization has only been extensively tested with MediaWiki 1.35. I just created a new branch `REL1_39` where I possibly fixed above error. I'm just about to move to 1.39 so expect more errors in the code in it's current state...
