### ISSUE TITLE
Templates and Forms

### ISSUE THREAD

**Issue by Spamtrap503** [oteloegen/SemanticOrganization#7]
Having issues with getting templates and forms onto pages. Running MW 1.39 (I know untested) but hoping you might have a fix for this so I don't have to start over at install. 

[e6cb6e9da81fb98d9bc696f7] /mediawiki/index.php?title=Users&action=submit Error: Call to undefined method Parser::getUser()

Backtrace:

from /var/lib/mediawiki/extensions/SemanticOrganization/SemanticOrganization.hooks.php(816)
#0 /var/lib/mediawiki/includes/parser/Parser.php(3437): SemanticOrganizationHooks::renderList()
#1 /var/lib/mediawiki/includes/parser/Parser.php(3122): Parser->callParserFunction()
#2 /var/lib/mediawiki/includes/parser/PPFrame_Hash.php(275): Parser->braceSubstitution()
#3 /var/lib/mediawiki/includes/parser/Parser.php(2951): PPFrame_Hash->expand()
#4 /var/lib/mediawiki/includes/parser/Parser.php(1609): Parser->replaceVariables()
#5 /var/lib/mediawiki/includes/parser/Parser.php(723): Parser->internalParse()
#6 /var/lib/mediawiki/includes/content/WikitextContentHandler.php(301): Parser->parse()
#7 /var/lib/mediawiki/includes/content/ContentHandler.php(1721): WikitextContentHandler->fillParserOutput()
#8 /var/lib/mediawiki/includes/content/Renderer/ContentRenderer.php(47): ContentHandler->getParserOutput()
#9 /var/lib/mediawiki/includes/EditPage.php(4535): MediaWiki\Content\Renderer\ContentRenderer->getParserOutput()
#10 /var/lib/mediawiki/includes/EditPage.php(4438): EditPage->doPreviewParse()
#11 /var/lib/mediawiki/includes/EditPage.php(3144): EditPage->getPreviewText()
#12 /var/lib/mediawiki/includes/EditPage.php(779): EditPage->showEditForm()
#13 /var/lib/mediawiki/includes/actions/EditAction.php(73): EditPage->edit()
#14 /var/lib/mediawiki/includes/actions/SubmitAction.php(38): EditAction->show()
#15 /var/lib/mediawiki/includes/MediaWiki.php(542): SubmitAction->show()
#16 /var/lib/mediawiki/includes/MediaWiki.php(322): MediaWiki->performAction()
#17 /var/lib/mediawiki/includes/MediaWiki.php(904): MediaWiki->performRequest()
#18 /var/lib/mediawiki/includes/MediaWiki.php(562): MediaWiki->main()
#19 /var/lib/mediawiki/index.php(50): MediaWiki->run()
#20 /var/lib/mediawiki/index.php(46): wfIndexMain()
#21 {main}

you said in a previous issue report that you are working on 1.39 and might have solved this problem. Any Advise?

Thanks

**Comment by thaider** [comment]
REL1_39 has been published in the meanwhile and seems to work fine. Please reopen, if the problem persists.
